apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/filipdadgar/gitopsDemo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
## Will be shown in the GUI for more kudos!
# SyncPolicy:
#   syncOptions:
#   - CreateNamespace=true
#   automated:
#     selfHeal: true
#     prune: true
